name: Quiz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  Quiz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd quiz && go build -v ./...

    - name: Unit Test
      env:
        TEST_BAD_QUIZ_FILE: "quiz/data/test_bad.csv"
        TEST_GOOD_QUIZ_FILE: "quiz/data/test_good.csv"
      run: pwd && cd quiz && go test -v ./...
