name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Quiz Build
      env:
        TEST_BAD_QUIZ_FILE: "${GITHUB_WORKSPACE}/quiz/data/test_bad.csv"
        TEST_GOOD_QUIZ_FILE: "${GITHUB_WORKSPACE}/quiz/data/test_good.csv"
      run: cd quiz && go build -v ./...

    - name: Test
      run: cd quiz && go test -v ./...
