name: Quiz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd quiz && go build -v ./...
  
  tests:
    runs-on: ubuntu-latest
    env:
      TEST_BAD_QUIZ_FILE: data/test_bad.csv
      TEST_GOOD_QUIZ_FILE: data/test_good.csv
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check Environment
      run: echo $TEST_BAD_QUIZ_FILE && echo $TEST_GOOD_QUIZ_FILE

    - name: Unit Tests
      run: cd quiz && TEST_BAD_QUIZ_FILE=data/test_bad.csv TEST_GOOD_QUIZ_FILE=data/test_good.csv go test ./...
