name: Quiz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd quiz && go build -v ./...
  
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Unit Tests
      run: TEST_BAD_QUIZ_FILE=${env.GITHUB_ACTION_PATH}/quiz/data/test_bad.csv |
           TEST_GOOD_QUIZ_FILE=${envGITHUB_ACTION_PATH}/quiz/data/test_good.csv && |
           cd quiz && go test -v ./...
